### PR TITLE
Ex1

### PR DESCRIPTION
**Pull request by SehedaOleh**
Task done. Could you please check it and give me some feedback. Thanks a lot.

### CODE REVIEW

**Comment by rikorsev** [comment]
Hi Oleh.

I have few notes regarding this pull request:
1) First of all, I have cloned your **EX_1** branch and tried to open the project file. Unfortunetelly, it looks that some thing wrong there.
project_issue
I think, you just forgot to add some necessary files to repository after some code refactoring(I didn't find main.c file in the repository).
To check that, please try to clone your project from git with this command:
**git clone --single-branch -b Ex1** https://github.com/SehedaOleh/GL_EmbeddedProCamp
on your PC(in some other directory then origin project directory) and try to open and build this project.

2) Usually, in the repositories **should** be stored only:
     -- source/header files, 
     -- files that necessary to built a project
     -- documentation and reference files.

Files that **should not** be stored in the repository:
     -- files that appears during compilation (object files, map files, binary files etc.);
     -- files that appears during using of your IDE (Keil) or build tool;

According to this, please remove following files from the repository:
    -- **Objects** directory (because it appears during compilation);
    -- **DebugConfig** directory (that contains some unnecessary config files that Keil has generated);
    -- **Proj1_Hello_world_STM32F303.uvguix.Oleh Se** (this is file that contains your GUI settings);

The best way to do that is following:
    -- add **.gitignore** in the root folder of the repositiry
    -- add following content in the **.gitignore** file:
           \*/Objects/\*
           \*/DebugConfig/\*
           \*uvguix\*
    -- run following command in the root of repositiry:
    **git rm -r --cached ./**    to unstage all files
   -- run following command in the root of repositiry:
    **git add -A**    to add all files that shouldn't be ignored.
   -- **git add .gitignore**
   -- commit changes

**Comment by SehedaOleh** [comment]
Could you please double check this task. I tried to clean-up all files and rebuild project.

**Review by rikorsev — CHANGES_REQUESTED** [review]
Hi Oleh.
Yes, now it is much more better. It works!
Only one thing. The repository still contains few unnecessary files:
- EventRecorderStub.scvd;
- Listing/Blinking_LED.map;
- startup_stm32f30x.lst;
Please remove it.

**Comment by SehedaOleh** [comment]
File deleted.

**Review by rikorsev — APPROVED** [review]

**Comment by rikorsev** [comment]
Hi Oleh. For some reason you have added STM32F30x_StdPeriph_Driver folder twice in the repo. Please remove one of it.

**Pull request merged**
